### PR TITLE
Fix deprecation warnings so that it can be used in the latest version

### PR DESCRIPTION
**Pull request by tgandrews**
This fixes issues #33 #31 #29 #27 #26 #23

I used the deprecations in the source code of [version 0.211](https://github.com/atom/atom/blob/v0.211.0/src/text-editor.coffee) to work out what we should be calling.

### CODE REVIEW

**Comment by chuckcarpenter** [comment]
:+1: on this one. Been missing this package since the update.

**Comment by roderickhsiao** [comment]
:+1: missing this package

**Comment by ng-webtools** [comment]
:+1:

**Comment by armandabric** [comment]
:+1:

**Comment by mhaamann** [comment]
:+1:

**Comment by splendido** [comment]
:+1:

**Comment by tgandrews** [comment]
Have released a new atom package as this package does not seem to be maintained anymore. https://atom.io/packages/atom-easy-jsdoc

**Pull request closed without merging**
